---
- name: Run app
  community.docker.docker_container:
    name: App
    image: hexletcomponents/devops-example-app
    ports:
      - "5000:5000"
    env:
      SERVER_MESSAGE: "{{ app_message }}"
