---
- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"

- name: Run app
  community.docker.docker_container:
    name: App
    image: dmitrykruglov/devops-example-app
    ports:
      - "5000:5000"
    env:
      SERVER_MESSAGE: "{{ app_message }}"
