---
- name: Run app
  community.docker.docker_container:
    name: App
    image: hexletcomponents/devops-example-app
    restart: yes
    pull: yes
    container_default_behavior: no_defaults
    published_ports:
      - "{{ app_port }}:5000"
    env:
      SERVER_MESSAGE: "{{ app_message }}"
